---
trigger:
  - none
pool:
  name: Default

resources:
  pipelines:
    - pipeline: buildApp   # a local alias you choose
      source: 'react-application-CI-pipeline'  # name of the first pipeline as it appears in DevOps
      project: 'rajeshsahuprivate' # optional if in same project
      branch: main         # optional if you only want main branch
      trigger:
        branches:
          include:
            - main   # this means “when PipelineA finishes on main branch”
steps:
  - script: >
      echo "Logging in to DockerHub..."

      echo "$(DOCKER_HUB_PASSWORD)" | docker login -u "$(DOCKER_HUB_USERNAME)" --password-stdin
       
       # Fetch the latest numeric tag from DockerHub
       IMAGE_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/$(DOCKER_HUB_USERNAME)/myreactapp/tags?page_size=100" \
       | jq -r '.results[].name' \
       | grep -E '^[0-9]+$' \
       | sort -n \
       | tail -1)

      echo "Latest DockerHub tag is: $IMAGE_TAG"


      # Set Azure DevOps variable for later steps

      echo "##vso[task.setvariable variable=IMAGE_TAG]$IMAGE_TAG"
    displayName: Get latest DockerHub image tag
    env:
      DOCKER_HUB_USERNAME: $(DOCKER_HUB_USERNAME)
      DOCKER_HUB_PASSWORD: $(DOCKER_HUB_PASSWORD)

  - script: |
      echo "Deploying to Minikube with Helm using IMAGE_TAG=$(IMAGE_TAG)"
      helm upgrade --install myreactapp ./react-helm-chart \
        --set image.tag=$(IMAGE_TAG) \
        --set image.repository=$(DOCKER_HUB_USERNAME)/myreactapp
    displayName: "Deploy Helm chart to Minikube"
